# -*- coding: utf-8 -*-
"""data plot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/147cXk7YzZR_YkW3Qp4IVVHo0TfNnpo2l
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
fi=pd.read_csv("bookprice.txt",header=None) #use file name
num=fi.to_numpy()
x_axis=num[:,0]
y_axis=num[:,1]
plt.scatter(x_axis,y_axis)
plt.show()